# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end

  lane :tests do
    run_tests(scheme: "BlueWallet")
  end


  lane :beta do
	  #build_app(scheme: "BlueWallet"), xcargs: "-allowProvisioningUpdates"
    #build_app(scheme: "BlueWallet")
    build_ios_app(scheme: "BlueWallet", clean: true)
   # upload_to_testflight(
   #    skip_waiting_for_build_processing: true
   # )
    #upload_to_testflight
  end

end